services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - pki-2fa-seed-data:/data
      - pki-2fa-cron-output:/cron-output

volumes:
  pki-2fa-seed-data:
  pki-2fa-cron-output:
